/*
 * ImageViewer.java
 *
 * Created on 5 avril 2007, 21:35
 */

package fr.jmmc.mcs;

import java.awt.image.IndexColorModel;

/**
 *
 * @author  mella
 */
public class ImageViewer extends javax.swing.JFrame {
    ImageCanvas imageCanvas;
    /** Creates new form ImageViewer */
    public ImageViewer() {
        initComponents();
        
        // add image canvas
        imageCanvas = new ImageCanvas();
        getContentPane().add(imageCanvas);
        
        // set items for colormodels
        colorModelComboBox.setModel(new javax.swing.DefaultComboBoxModel(ColorModels.colorModelNames));
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        colorModelComboBox = new javax.swing.JComboBox();
        infoTextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setText("Color model:");
        jPanel1.add(jLabel1);

        colorModelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorModelComboBoxActionPerformed(evt);
            }
        });

        jPanel1.add(colorModelComboBox);

        infoTextfield.setEditable(false);
        infoTextfield.setBorder(null);
        jPanel1.add(infoTextfield);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorModelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorModelComboBoxActionPerformed
        imageCanvas.setColorModel(ColorModels.colorModels[colorModelComboBox.getSelectedIndex()]);
    }//GEN-LAST:event_colorModelComboBoxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImageViewer  viewer = new ImageViewer();
                viewer.setVisible(true);
                viewer.setDefaultCloseOperation(viewer.EXIT_ON_CLOSE);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox colorModelComboBox;
    private javax.swing.JTextField infoTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
