/*******************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ******************************************************************************/
/*
 * TabbedPanel.java
 *
 * Created on 13 novembre 2006, 17:10
 */
package fr.jmmc.mf.gui;

import fr.jmmc.jmcs.gui.util.SwingUtils;
import java.awt.Font;

/**
 *
 * @author  mella
 */
public class TabbedPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify                     
    /**
     * DOCUMENT ME!
     */
    private javax.swing.JButton closeButton;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JTextField dateTextField;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JPanel jPanel1;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane jScrollPane1;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JEditorPane resultPane;

    /**
     * Creates new form TabbedPanel
     */
    public TabbedPanel(String result) {
        initComponents();

        // Adjust fonts:
        dateTextField.setFont(new Font(Font.DIALOG, Font.PLAIN, SwingUtils.adjustUISize(10)));

        resultPane.setText(result);
        dateTextField.setText(new java.util.Date().toString());
    }

    /**
     * DOCUMENT ME!
     *
     * @param url DOCUMENT ME!
     *
     * @throws Exception DOCUMENT ME!
     */
    public void setPage(String url) throws Exception {
        resultPane.setPage(url);
    }

    /**
     * DOCUMENT ME!
     *
     * @param url DOCUMENT ME!
     *
     * @throws Exception DOCUMENT ME!
     */
    public void setPage(java.net.URL url) throws Exception {
        resultPane.setPage(url);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1           = new javax.swing.JPanel();
        dateTextField     = new javax.swing.JTextField();
        closeButton       = new javax.swing.JButton();
        jScrollPane1      = new javax.swing.JScrollPane();
        resultPane        = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        dateTextField.setEditable(false);
        dateTextField.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel1.add(dateTextField);

        closeButton.setText("Close this tab");
        closeButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    closeButtonActionPerformed(evt);
                }
            });

        jPanel1.add(closeButton);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        resultPane.setEditable(false);
        jScrollPane1.setViewportView(resultPane);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)    {//GEN-FIRST:event_closeButtonActionPerformed
        MFGui.closeTab(this);
    }//GEN-LAST:event_closeButtonActionPerformed

    // End of variables declaration                   
}
