/*
 * FilesPanel.java
 *
 * Created on 6 décembre 2006, 11:33
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mcs.gui.ShowHelpAction;
import fr.jmmc.mf.gui.models.SettingsModel;

import fr.jmmc.mcs.util.ActionRegistrar;
import fr.jmmc.mf.gui.actions.LoadDataFilesAction;
import fr.jmmc.mf.models.Files;

import javax.swing.*;
import javax.swing.tree.TreePath;


/**
 *
 * @author  mella
 */
public class FilesPanel extends javax.swing.JPanel
{
    /**
     * DOCUMENT ME!
     */
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.FilesPanel");
    static Files current = null;
    SettingsViewerInterface settingsViewer = null;
    public static Action loadFilesAction;
    SettingsModel rootSettingsModel = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileButton;
    private javax.swing.JList fileList;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /** Creates new form FilesPanel */
    public FilesPanel(SettingsViewerInterface viewer)
    {
        settingsViewer      = viewer;
        loadFilesAction     = ActionRegistrar.getInstance().get(LoadDataFilesAction.className, LoadDataFilesAction.actionName);
        initComponents();
        addFileButton.setAction(loadFilesAction);
        jButton1.setAction(new ShowHelpAction("_Load_Oifile_Bt_ou_Area"));
    }

    /**
     * DOCUMENT ME!
     *
     * @param f DOCUMENT ME!
     * @param s DOCUMENT ME!
     */
    public void show(Files f, SettingsModel s)
    {
        current           = f;
        rootSettingsModel     = s;
        logger.fine("Showing list of " + current.getFileCount() + " files");

        // update model because it could have been modified
        fileList.setModel(s.allFilesListModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList();
        addFileButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Oifile list"));
        setLayout(new java.awt.GridBagLayout());

        fileList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fileList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        addFileButton.setAction(loadFilesAction);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(addFileButton, gridBagConstraints);

        jButton1.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void fileListMouseClicked(java.awt.event.MouseEvent evt)
    {
        if (evt.getClickCount() == 2)
        {
            if (fileList.getSelectedValue() == null)
            {
                loadFilesAction.actionPerformed(null);
            }
            else
            {
                rootSettingsModel.setSelectionPath(
                    new TreePath(new Object[]{
                rootSettingsModel,
                current,
                fileList.getSelectedValue() } ));
            }
        }
    } // </editor-fold>                              
}
