/*
 * FitterPanel.java
 *
 * Created on 11 janvier 2007, 12:40
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mf.models.Settings;


/**
 *
 * @author  mella
 */
public class FitterPanel extends javax.swing.JPanel
{
    /**
     * DOCUMENT ME!
     */
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.FitterPanel");

    /**
     * DOCUMENT ME!
     */
    Settings current = null;

    /**
     * DOCUMENT ME!
     */
    SettingsViewerInterface settingsViewer = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * DOCUMENT ME!
     */
    private javax.swing.JComboBox fitterComboBox;

    /** Creates new form FitterPanel */
    public FitterPanel(SettingsViewerInterface viewer)
    {
        settingsViewer = viewer;
        initComponents();
    }

    /**
     * DOCUMENT ME!
     *
     * @param s DOCUMENT ME!
     */
    public void show(Settings s)
    {
        logger.entering("" + this.getClass(), "show");
        current = s;

        if (s.getFitter() != null)
        {
            fitterComboBox.setSelectedItem(s.getFitter());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        fitterComboBox = new javax.swing.JComboBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        setBorder(javax.swing.BorderFactory.createTitledBorder("Fitter setup"));
        fitterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "standard" }));
        fitterComboBox.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    fitterComboBoxActionPerformed(evt);
                }
            });

        add(fitterComboBox);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void fitterComboBoxActionPerformed(java.awt.event.ActionEvent evt)
    { //GEN-FIRST:event_fitterComboBoxActionPerformed
        logger.entering("" + this.getClass(), "fitterComboBoxActionPerformed");
        current.setFitter((String) fitterComboBox.getSelectedItem());
    } //GEN-LAST:event_fitterComboBoxActionPerformed

    // End of variables declaration//GEN-END:variables
}
