/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define mfmdlERR_INDEX_OUT_OF_BOUNDS 1   /**<  %80s given index %d range is [%d,%d] */
#define mfmdlERR_WRONG_PARAMETER_NAME 2   /**<  '%80s' parameter unknown */
#define mfmdlERR_ALLOC_MEM 4   /**<  Could not allocate %d bytes */
#define mfmdlERR_REALLOC_MEM 5   /**<  Could not reallocate vector %p */
