/*
 JMMC
*/
/*
 * enginePanel.java
 *
 * Created on 26 juillet 2006, 09:25
 */
package jmmc.mf.gui;

import jmmc.mf.svr.*;
import jmmc.mcs.log.MCSLogger;
import jmmc.mcs.gui.ReportDialog;
/**
 *
 * @author  mella
 */
public class EnginePanel extends javax.swing.JPanel
{
    // Variables declaration - do not modify                     
    private javax.swing.JLabel              chi2Label;
    private javax.swing.JFormattedTextField chi2TextField;
    private javax.swing.JButton             doAllStepsButton;
    private javax.swing.JButton             doNextStepButton;
    private javax.swing.JButton             doNextStepsButton;
    private javax.swing.JButton             jButton1;
    private javax.swing.JLabel              stepLabel;
    private javax.swing.JSpinner            stepSpinner;
    private javax.swing.JFormattedTextField stepTextField;

    /** Creates new form enginePanel */
    public EnginePanel()
{
        initComponents();
        stepTextField.setValue(new Double("0"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        doNextStepButton      = new javax.swing.JButton();
        doNextStepsButton     = new javax.swing.JButton();
        jButton1              = new javax.swing.JButton();
        stepSpinner           = new javax.swing.JSpinner();
        chi2Label             = new javax.swing.JLabel();
        stepLabel             = new javax.swing.JLabel();
        stepTextField         = new javax.swing.JFormattedTextField();
        chi2TextField         = new javax.swing.JFormattedTextField();
        doAllStepsButton      = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        doNextStepButton.setText("Do one Step");
        doNextStepButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    doNextStepButtonActionPerformed(evt);
                }
            });

        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 2;
        gridBagConstraints.gridwidth     = 2;
        gridBagConstraints.fill          = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx         = 10;
        add(doNextStepButton, gridBagConstraints);

        doNextStepsButton.setText("Do next Steps");
        doNextStepsButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    doNextStepsButtonActionPerformed(evt);
                }
            });

        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 0;
        gridBagConstraints.gridy     = 3;
        gridBagConstraints.fill      = java.awt.GridBagConstraints.HORIZONTAL;
        add(doNextStepsButton, gridBagConstraints);

        jButton1.setText("Abort");
        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 4;
        gridBagConstraints.gridwidth     = 2;
        gridBagConstraints.fill          = java.awt.GridBagConstraints.HORIZONTAL;
        add(jButton1, gridBagConstraints);

        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 1;
        gridBagConstraints.gridy     = 3;
        gridBagConstraints.fill      = java.awt.GridBagConstraints.HORIZONTAL;
        add(stepSpinner, gridBagConstraints);

        chi2Label.setText("Chi2/dof:");
        chi2Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 0;
        gridBagConstraints.gridy     = 6;
        add(chi2Label, gridBagConstraints);

        stepLabel.setText("Steps:");
        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 0;
        gridBagConstraints.gridy     = 5;
        add(stepLabel, gridBagConstraints);

        stepTextField.setBorder(null);
        stepTextField.setEditable(false);
        stepTextField.setText("jFormattedTextField1");
        gridBagConstraints             = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx       = 1;
        gridBagConstraints.gridy       = 5;
        gridBagConstraints.fill        = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx     = 1.0;
        add(stepTextField, gridBagConstraints);

        chi2TextField.setBorder(null);
        chi2TextField.setEditable(false);
        chi2TextField.setText("jFormattedTextField1");
        gridBagConstraints           = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx     = 1;
        gridBagConstraints.gridy     = 6;
        gridBagConstraints.fill      = java.awt.GridBagConstraints.HORIZONTAL;
        add(chi2TextField, gridBagConstraints);

        doAllStepsButton.setText("Run");
        gridBagConstraints               = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx         = 0;
        gridBagConstraints.gridy         = 0;
        gridBagConstraints.gridwidth     = 2;
        gridBagConstraints.fill          = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx         = 10;
        add(doAllStepsButton, gridBagConstraints);
    }

    // </editor-fold>//GEN-END:initComponents
    private void incrementStep(int nbSteps) {
        MCSLogger.trace();
        double d = ((Double) stepTextField.getValue()).doubleValue();
        stepTextField.setValue(new Double(d + nbSteps));
    }
    
    private void doNextStepsButtonActionPerformed(
            java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_doNextStepsButtonActionPerformed
        MCSLogger.trace();
        try {
            
            int i = ((Integer) stepSpinner.getValue()).intValue();
            ServerImpl.donextstep(i);
            incrementStep(i);
        } catch (Exception e) {
            new ReportDialog(new javax.swing.JFrame(), true, e).setVisible(true);
        }
    }//GEN-LAST:event_doNextStepsButtonActionPerformed
    
    private void doNextStepButtonActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_doNextStepButtonActionPerformed
        MCSLogger.trace();
        try {
            ServerImpl.donextstep(1);
            incrementStep(1);
        } catch (Exception e) {
            new ReportDialog(new javax.swing.JFrame(), true, e).setVisible(true);
        }
    }//GEN-LAST:event_doNextStepButtonActionPerformed

    // End of variables declaration                   
}
