/*******************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ******************************************************************************/
/*
 * FitterPanel.java
 *
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mf.models.Settings;

public class FitterPanel extends javax.swing.JPanel {

    /**
     * Main logger.
     */
    static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            FitterPanel.class.getName());
    Settings current = null;
    SettingsViewerInterface settingsViewer = null;

    /** Creates new form FitterPanel */
    public FitterPanel(SettingsViewerInterface viewer) {
        settingsViewer = viewer;
        initComponents();
    }

    public void show(Settings s) {        
        current = s;

        if (s.getFitter() != null) {
            fitterComboBox.setSelectedItem(s.getFitter());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        fitterComboBox = new javax.swing.JComboBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        setBorder(javax.swing.BorderFactory.createTitledBorder("Fitter setup"));
        fitterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "standard" }));
        fitterComboBox.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    fitterComboBoxActionPerformed(evt);
                }
            });

        add(fitterComboBox);
    } // </editor-fold>//GEN-END:initComponents

    private void fitterComboBoxActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_fitterComboBoxActionPerformed
        current.setFitter((String) fitterComboBox.getSelectedItem());
    }//GEN-LAST:event_fitterComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fitterComboBox;
    // End of variables declaration//GEN-END:variables
}
