/*
 * ParametersPanel.java
 *
 * Created on 4 janvier 2007, 15:11
 */
package fr.jmmc.mf.gui;


import fr.jmmc.mf.gui.models.ParametersTableModel;
import fr.jmmc.mf.gui.models.SettingsModel;
import fr.jmmc.mf.models.Parameter;
import fr.jmmc.mf.models.Parameters;


import javax.swing.*;


/**
 *
 * @author  mella
 */
public class ParametersPanel extends javax.swing.JPanel
{
    /**
     * DOCUMENT ME!
     */
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.ModelPanel");
    Parameters              current;
    SettingsViewerInterface settingsViewer = null;
    DefaultListModel parameterListModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable sharedParametersTable;
    // End of variables declaration//GEN-END:variables
    
    /** Creates new form ParametersPanel */
    public ParametersPanel(SettingsViewerInterface viewer)
    {
        parameterListModel = new DefaultListModel();
        initComponents();
    }

    public void show(SettingsModel s, Parameters p)
    {
        current = p;
        parameterListModel.clear();
        Parameter[] params = current.getParameter();
        ParametersTableModel sharedTableModel = new ParametersTableModel();
        sharedTableModel.setModel(s, params,true);
        sharedParametersTable.setModel(sharedTableModel);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        sharedParametersTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter list"));
        setLayout(new java.awt.GridBagLayout());

        sharedParametersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sharedParametersTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(jScrollPane2, gridBagConstraints);

        jLabel1.setText("Shared parameters:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
}
