/*
 * ParametersPanel.java
 *
 * Created on 4 janvier 2007, 15:11
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mcs.gui.FeedbackReport;

import fr.jmmc.mf.models.Parameter;
import fr.jmmc.mf.models.Parameters;

import java.util.*;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;


/**
 *
 * @author  mella
 */
public class ParametersPanel extends javax.swing.JPanel
{
    /**
     * DOCUMENT ME!
     */
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.ModelPanel");

    //ParametersTableModel parametersTableModel;
    /**
     * DOCUMENT ME!
     */
    Parameters              current;

    /**
     * DOCUMENT ME!
     */
    SettingsViewerInterface settingsViewer = null;

    /**
     * DOCUMENT ME!
     */
    DefaultListModel parameterListModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * DOCUMENT ME!
     */
    private javax.swing.JScrollPane jScrollPane1;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JList parameterList;

    /** Creates new form ParametersPanel */
    public ParametersPanel(SettingsViewerInterface viewer)
    {
        parameterListModel = new DefaultListModel();
        initComponents();
    }

    /**
     * DOCUMENT ME!
     *
     * @param p DOCUMENT ME!
     */
    public void show(Parameters p)
    {
        current = p;

        parameterListModel.clear();

        Parameter[] params = current.getParameter();

        for (int i = 0; i < params.length; i++)
        {
            parameterListModel.addElement(params[i]);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1      = new javax.swing.JScrollPane();
        parameterList     = new javax.swing.JList();

        setLayout(new java.awt.GridBagLayout());

        setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter list"));
        parameterList.setModel(parameterListModel);
        parameterList.setEnabled(false);
        parameterList.setFocusable(false);
        jScrollPane1.setViewportView(parameterList);

        gridBagConstraints             = new java.awt.GridBagConstraints();
        gridBagConstraints.fill        = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx     = 1.0;
        gridBagConstraints.weighty     = 1.0;
        add(jScrollPane1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    // End of variables declaration//GEN-END:variables
}
