/*
 * PlotPanel.java
 *
 * Created on 29 oct. 2008, 08:16:23
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mf.models.Parameter;

/**
 *
 * @author mella
 */
public class PlotChi2Panel extends javax.swing.JPanel
{

    /** Class logger */
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.PlotChi2Panel");
    public SettingsModel settingsModel = null;

    /** Creates new form PlotPanel */
    public PlotChi2Panel()
    {
        initComponents();
    }

    public void show(SettingsModel s)
    {
        settingsModel = s;
        Object[] params = s.getParameterListModel().toArray();
        xComboBox.removeAllItems();
        yComboBox.removeAllItems();
        for (int i = 0; i < params.length; i++)
        {
            Parameter p = (Parameter) params[i];
            if (!p.getHasFixedValue()){
                xComboBox.addItem(p);
                yComboBox.addItem(p);               
            }
        }
        boolean hasParam = xComboBox.getItemCount()!=0;
        plot1DChi2Button.setEnabled(hasParam);
        plot2DChi2Button.setEnabled(hasParam);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        plot1DChi2Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        xminFormattedTextField = new javax.swing.JFormattedTextField();
        xmaxFormattedTextField = new javax.swing.JFormattedTextField();
        xSamplingFormattedTextField = new javax.swing.JFormattedTextField();
        plot2DChi2Button = new javax.swing.JButton();
        ySamplingFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        yminFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ymaxFormattedTextField = new javax.swing.JFormattedTextField();
        xComboBox = new javax.swing.JComboBox();
        yComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Plot chi2 panel"));
        setLayout(new java.awt.GridBagLayout());

        plot1DChi2Button.setText("Plot 1D chi2");
        plot1DChi2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plot1DChi2ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(plot1DChi2Button, gridBagConstraints);

        jLabel3.setText("max");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        add(jLabel3, gridBagConstraints);

        jLabel5.setText("sampling");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("min");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        add(jLabel6, gridBagConstraints);

        xminFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        xminFormattedTextField.setText("-50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(xminFormattedTextField, gridBagConstraints);

        xmaxFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        xmaxFormattedTextField.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(xmaxFormattedTextField, gridBagConstraints);

        xSamplingFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        xSamplingFormattedTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(xSamplingFormattedTextField, gridBagConstraints);

        plot2DChi2Button.setText("Plot 2D chi2");
        plot2DChi2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plot2DChi2ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(plot2DChi2Button, gridBagConstraints);

        ySamplingFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ySamplingFormattedTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(ySamplingFormattedTextField, gridBagConstraints);

        jLabel7.setText("sampling");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        add(jLabel7, gridBagConstraints);

        yminFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        yminFormattedTextField.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(yminFormattedTextField, gridBagConstraints);

        jLabel8.setText("max");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        add(jLabel8, gridBagConstraints);

        jLabel10.setText("min");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        add(jLabel10, gridBagConstraints);

        ymaxFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ymaxFormattedTextField.setText("50");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(ymaxFormattedTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(xComboBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(yComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void plot1DChi2ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_plot1DChi2ButtonActionPerformed
    {//GEN-HEADEREND:event_plot1DChi2ButtonActionPerformed
    
        String args = ((Parameter)xComboBox.getSelectedItem()).getName()
                +" " + xminFormattedTextField.getText()
                + " " + xmaxFormattedTextField.getText()
                + " " + xSamplingFormattedTextField.getText();        
        PlotPanel.plot("getChi2Map", args, "1D Chi2 Slice");
}//GEN-LAST:event_plot1DChi2ButtonActionPerformed

    private void plot2DChi2ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_plot2DChi2ButtonActionPerformed
    {//GEN-HEADEREND:event_plot2DChi2ButtonActionPerformed
        String args = ((Parameter)xComboBox.getSelectedItem()).getName()
                +" " + xminFormattedTextField.getText()
                + " " + xmaxFormattedTextField.getText()
                + " " + xSamplingFormattedTextField.getText()
                +" '"+((Parameter)yComboBox.getSelectedItem()).getName()
                +"' " + yminFormattedTextField.getText()
                + " " + ymaxFormattedTextField.getText()
                + " " + ySamplingFormattedTextField.getText();
        PlotPanel.plot("getChi2Map", args, "2D Chi2 Slice");
}//GEN-LAST:event_plot2DChi2ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton plot1DChi2Button;
    private javax.swing.JButton plot2DChi2Button;
    private javax.swing.JComboBox xComboBox;
    private javax.swing.JFormattedTextField xSamplingFormattedTextField;
    private javax.swing.JFormattedTextField xmaxFormattedTextField;
    private javax.swing.JFormattedTextField xminFormattedTextField;
    private javax.swing.JComboBox yComboBox;
    private javax.swing.JFormattedTextField ySamplingFormattedTextField;
    private javax.swing.JFormattedTextField ymaxFormattedTextField;
    private javax.swing.JFormattedTextField yminFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
