/*
 * JMMC
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mcs.gui.FeedbackReport;
import fr.jmmc.mcs.util.*;

import fr.jmmc.mf.models.Settings;

import java.awt.event.ActionEvent;

import java.io.StringReader;

import java.lang.reflect.*;

import java.util.*;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import javax.swing.tree.*;


/**
 *
 * @author  mella
 */
public class SettingsPanel extends javax.swing.JPanel
{
    /**
     * DOCUMENT ME!
     */
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.SettingsPanel");

    /**
     * DOCUMENT ME!
     */
    FilesPanel filesPanel = null;

    /**
     * DOCUMENT ME!
     */
    TargetsPanel targetsPanel = null;

    /**
     * DOCUMENT ME!
     */
    FitterPanel fitterPanel = null;

    /**
     * DOCUMENT ME!
     */
    UserInfoPanel userInfoPanel = null;

    /**
     * DOCUMENT ME!
     */
    Settings current = null;

    // Variables declaration - do not modify                     
    /**
     * DOCUMENT ME!
     */
    private javax.swing.JSplitPane jSplitPane1;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JSplitPane jSplitPane2;

    /**
     * DOCUMENT ME!
     */
    private javax.swing.JSplitPane jSplitPane3;

    /** Creates new form ModelPanel */
    public SettingsPanel(FilesPanel fp, TargetsPanel tp, FitterPanel fitp, UserInfoPanel uip)
    {
        filesPanel        = fp;
        targetsPanel      = tp;
        fitterPanel       = fitp;
        userInfoPanel     = uip;
        initComponents();
    }

    /**
     * DOCUMENT ME!
     *
     * @param s DOCUMENT ME!
     * @param sm DOCUMENT ME!
     */
    public void show(Settings s, SettingsModel sm)
    {
        logger.entering("" + this.getClass(), "show");
        current = s;

        // @todo check why next lines are required
        // !(( why component disapears???  does their parent change or???
        jSplitPane2.setTopComponent(filesPanel);

        if (current.getFiles().getFileCount() >= 1)
        {
            jSplitPane2.setBottomComponent(targetsPanel);
            jSplitPane3.setTopComponent(fitterPanel);
        }
        else
        {
            logger.finest("Current settings has no file");
            jSplitPane2.setBottomComponent(null);
            jSplitPane3.setTopComponent(null);
        }

        jSplitPane3.setBottomComponent(userInfoPanel);

        // Set File list
        filesPanel.show(current.getFiles(), sm);
        // Set Target List
        targetsPanel.show(current.getTargets(), sm);
        // Set fitter
        fitterPanel.show(current);
        // Set userInfo
        userInfoPanel.show(current);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jSplitPane1     = new javax.swing.JSplitPane();
        jSplitPane2     = new javax.swing.JSplitPane();
        jSplitPane3     = new javax.swing.JSplitPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(javax.swing.BorderFactory.createTitledBorder("Settings panel"));
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane2.setBorder(null);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);
        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setBorder(null);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setRightComponent(jSplitPane3);

        add(jSplitPane1);
    } // </editor-fold>//GEN-END:initComponents

    // End of variables declaration                   
}
