/*
 * JMMC
 */
package jmmc.mf.gui;

import jmmc.mcs.gui.ReportDialog;
import jmmc.mcs.util.*;

import jmmc.mf.models.*;

import jmmc.mf.svr.*;

import java.awt.event.ActionEvent;

import java.io.StringReader;

import java.util.*;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import javax.swing.tree.*;

import java.lang.reflect.*;

/**
 *
 * @author  mella
 */
public class SettingsPanel extends javax.swing.JPanel
{   
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger("jmmc.mf.gui.SettingsPanel");
    Settings current=null;
    /** Creates new form ModelPanel */
    public SettingsPanel() {
        initComponents();
    }   
    
    public void show(Settings s){
        current = s;
        if (s.getFitter()!= null){
            fitterComboBox.setSelectedItem(s.getFitter());                    
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        addFileButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        addTargetButton = new javax.swing.JButton();
        targetNameComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        fitterComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createTitledBorder("Settings panel"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("File list"));
        jList1.setModel(SettingsModel.allFilesListModel);
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane1, gridBagConstraints);

        addFileButton.setAction(MainFrame.getSettingsModel().loadFilesAction);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(addFileButton, gridBagConstraints);

        jPanel2.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Target list"));
        jList2.setModel(SettingsModel.targetListModel);
        jScrollPane2.setViewportView(jList2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jScrollPane2, gridBagConstraints);

        addTargetButton.setText("Add new target");
        addTargetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTargetButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(addTargetButton, gridBagConstraints);

        targetNameComboBox.setModel(SettingsModel.oiTargets);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(targetNameComboBox, gridBagConstraints);

        jPanel2.add(jPanel5);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fitter setup"));
        fitterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "standard" }));
        fitterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitterComboBoxActionPerformed(evt);
            }
        });

        jPanel1.add(fitterComboBox);

        jPanel2.add(jPanel1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void addTargetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTargetButtonActionPerformed
        Target t = new Target();
        t.setIdent(""+targetNameComboBox.getSelectedItem());
        current.getTargets().addTarget(t);
        logger.fine("Adding on target to current settings");
        // fire tree event to refresh
        MainFrame.rootSettingsModel.fireUpdate();                
    }//GEN-LAST:event_addTargetButtonActionPerformed

    private void fitterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitterComboBoxActionPerformed
        current.setFitter((String)fitterComboBox.getSelectedItem());
    }//GEN-LAST:event_fitterComboBoxActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileButton;
    private javax.swing.JButton addTargetButton;
    private javax.swing.JComboBox fitterComboBox;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox targetNameComboBox;
    // End of variables declaration//GEN-END:variables
    
}
