/*
 * ResultPanel.java
 *
 * Created on 13 novembre 2006, 17:10
 */

package jmmc.mf.gui;

/**
 *
 * @author  mella
 */
public class ResultPanel extends javax.swing.JPanel {
    
    /** Creates new form ResultPanel */
    public ResultPanel(String result) {
        initComponents();
        resultTextArea.setText(result);
        dateTextField.setText(""+new java.util.Date());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        dateTextField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        dateTextField.setEditable(false);
        jPanel1.add(dateTextField);

        closeButton.setText("Close this tab");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jPanel1.add(closeButton);

        add(jPanel1, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        MainFrame.closeTab(this);
        
    }//GEN-LAST:event_closeButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultTextArea;
    // End of variables declaration//GEN-END:variables
    
}
