/*
 * UserInfoPanel.java
 *
 * Created on 11 janvier 2007, 12:48
 */
package fr.jmmc.mf.gui;

import fr.jmmc.mf.models.*;


/**
 *
 * @author  mella
 */
public class UserInfoPanel extends javax.swing.JPanel {
    static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(
            "fr.jmmc.mf.gui.UserInfoPanel");
    Settings current = null;
    SettingsViewerInterface settingsViewer = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea userInfoTextArea;

    /** Creates new form UserInfoPanel */
    public UserInfoPanel(SettingsViewerInterface viewer) {
        settingsViewer = viewer;
        initComponents();
    }

    public void show(Settings s) {
        logger.entering("" + this.getClass(), "show");
        current = s;

        if (s.getUserInfo() != null) {
            userInfoTextArea.setText(s.getUserInfo());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        userInfoTextArea = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        setBorder(javax.swing.BorderFactory.createTitledBorder("User info:"));
        userInfoTextArea.setColumns(20);
        userInfoTextArea.setRows(5);
        userInfoTextArea.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    userInfoTextAreaCaretUpdate(evt);
                }
            });

        jScrollPane1.setViewportView(userInfoTextArea);

        add(jScrollPane1);
    } // </editor-fold>//GEN-END:initComponents

    private void userInfoTextAreaCaretUpdate(javax.swing.event.CaretEvent evt) { //GEN-FIRST:event_userInfoTextAreaCaretUpdate
                                                                                 //logger.entering(""+this.getClass(), "userInfoTextAreaCaretUpdate");
        current.setUserInfo(userInfoTextArea.getText());
    } //GEN-LAST:event_userInfoTextAreaCaretUpdate

    // End of variables declaration//GEN-END:variables
}
